ALTER TABLE events ADD COLUMN IF NOT EXISTS highlights TEXT[] DEFAULT '{}';
ALTER TABLE events ADD COLUMN IF NOT EXISTS what_to_bring TEXT[] DEFAULT '{}';
ALTER TABLE events ADD COLUMN IF NOT EXISTS schedule JSONB DEFAULT '[]';
